#!/usr/bin/env python
"""
Usage:
    knackered (--help | --version)
    knackered

Options:
    --help         Show this help message
    --version      Show version information
"""
from docopt import docopt

import knackered


def main():
    args = docopt(__doc__, version="knackered %s" % knackered.__version__)
    print args


if __name__ == "__main__":
    main()
