#!/usr/bin/env python
"""
Usage:
    knackered (--help | --version)
    knackered [-c <config>]

Options:
    --help                  Show this help message
    --version               Show version information
    -c --config=<config>    The config file to load [default: /etc/knackered/engine.ini]
"""
from docopt import docopt

import knackered


def main():
    args = docopt(__doc__, version="knackered %s" % knackered.__version__)
    print args


if __name__ == "__main__":
    main()
