#!/usr/bin/env python
"""
Usage:
    knackered (--help | --version)
    knackered [-c <config>]

Options:
    --help                  Show this help message
    --version               Show version information
    -c --config=<config>    The config file to load [default: /etc/knackered/engine.ini]
"""
from docopt import docopt

from knackered import __version__
from knackered.app import create_app
from knackered.settings import Settings


def main():
    args = docopt(__doc__, version="knackered %s" % __version__)
    settings = Settings(args["--config"])
    app = create_app(settings)
    app.run()


if __name__ == "__main__":
    main()
